/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const CompanyStats = IDL.Record({
  'yearsExperience' : IDL.Nat,
  'clientsServed' : IDL.Nat,
  'projectsCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([IDL.Text], [IDL.Vec(Contact)], ['query']),
  'getCompanyStats' : IDL.Func([], [CompanyStats], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CompanyStats = IDL.Record({
    'yearsExperience' : IDL.Nat,
    'clientsServed' : IDL.Nat,
    'projectsCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([IDL.Text], [IDL.Vec(Contact)], ['query']),
    'getCompanyStats' : IDL.Func([], [CompanyStats], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };