/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyStats {
  'yearsExperience' : bigint,
  'clientsServed' : bigint,
  'projectsCompleted' : bigint,
}
export interface Contact {
  'serviceType' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface _SERVICE {
  'getAllEnquiries' : ActorMethod<[string], Array<Contact>>,
  'getCompanyStats' : ActorMethod<[], CompanyStats>,
  'login' : ActorMethod<[string, string], string>,
  'logout' : ActorMethod<[string], undefined>,
  'submitEnquiry' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];